### ISSUE TITLE
Purchase with Escrow/Mod resulted in error & direct payment is not updating status

### ISSUE THREAD

**Issue by webunraveling** [OpenBazaar/openbazaar-desktop#1525]
Brief Description: After attempting to make a purchase with the option for moderation, I received an error (something that made me think it had to do with escrow... can't remember the error) and then decided to do a direct sale since it is a trusted vendor... the OpenBazaar BCH store. So a sale with no option for moderation/escrow was placed. There was no error this time. Instead I was presented with a QR/wallet to send payment to. Payment was sent immediately. After several verifications on the BCH blockchain, OpenBazaar still asks for payment. The payment shows up on the blockchain with several confirmations but I still see the order status of "Awaiting Payment". Right now, the vendor sees the "Fulfilled" status. Unfortunately, I don't have the log files from this time. Let me know if the most recent log files will be of any use.

Operating System (OS and version): Debian
OpenBazaar version: 2.2.3 (upgraded to 2.2.4 and it still hasn't synced)

Observed Behavior: OpenBazaar still thinks I haven't paid. 

Expected Behavior: The order status should say I have paid. 

Additional info (links, images, etc go here):
[Screenshot](https://i.imgur.com/lJjQ2JW.jpg) of my (buyer's) screen after payment has been made.

**Comment by jjeffryes** [comment]
@webunraveling can you go into settings/advanced, and click the Reload Transactions button? That should resync your local data and change your order status to paid.

**Comment by jjeffryes** [comment]
If resyncing doesn't correct this, there are some other steps we can take.

**Comment by webunraveling** [comment]
Thanks for the suggestion. I've tried the Reloading Transaction button twice now and the status still shows "Awaiting Payment".

**Comment by jjeffryes** [comment]
@webunraveling can you try the following?

1. Make sure the OpenBazaar app is turned off.
2. Find your OpenBazaar2.0 directory.
3. Delete the headers.bin file in the OpenBazaar2.0 directory.
4. Turn the OpenBazaar app back on.
5. In settings/advanced, if you click the Show Block Data button, you can see the current state of synching your node to the blockchain. If you compare the height to the latest block in a block explorer like https://blockexplorer.com/, you'll see when it's completely synced (the height will be equal to the latest block).

After your node has completely synced, your payment should show up again, if it doesn't, there is a more serious problem and our server team will have to dig into your logs and possibly get other data from you.

**Comment by jjeffryes** [comment]
We just released version 2.2.4, which fixed a bug that would sometimes cause syncing to get stuck, that might be what happened to you. Can you try updating and then see if it syncs?

The update should happen automatically once it's released tonight.

**Comment by webunraveling** [comment]
This originally occurred on 2.2.3. I upgraded to 2.2.4-rc1 and now to 2.2.4 and its still showing a status of "Awaiting Payment". It looks like it synced up to the latest BTC block at least. :man_shrugging:

**Comment by jjeffryes** [comment]
If it's a BCH node, it should be syncing with the BCH chain.

**Comment by jjeffryes** [comment]
@cpacia @placer14 @tyler-smith any thoughts on why this payment isn't showing up after what's been tried above?

**Comment by placer14** [comment]
Yes. @webunraveling posted `rm ~/.openbazaar2.0/headers.bin` in the backlog. Is it possible you're removing the wrong headers.bin? If you're using a BCH node, you should be doing `rm ~/.OpenBazaar2.0-bitcoincash/headers.bin` according to https://openbazaar.zendesk.com/hc/en-us/articles/115002761312-How-do-I-backup-my-store-

**Comment by placer14** [comment]
Also, please verify in the `logs/bitcoin.log` that the chain sync completed.

**Comment by webunraveling** [comment]
Thanks for the additional suggestion, @placer14. I almost tried that but figured I'd stick to the instructions. A side note, just to verify, the BCH node is syncing to the most recent height of the BCH blockchain. To verify, below is the output of `cat ~/.openbazaar2.0-bitcoincash/logs/bitcoin.log | tail -20` although after deleting headers.bin it had to sync up with the blockchain again. It still shows the order status of "Awaiting Payment". Should I reload my transactions again as well again?

    10:02:14.298 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 00000000000000000087078a7aa0bee64c7ab9bc414c8a80186747a69ba42f04 at height 543963
    10:02:14.301 [DEBUG] [bitcoin/handleMerkleBlockMsg] Requesting block 000000000000000001b354ea9893bdbd317923adc51ad7e0e0fc59f55f97a830, len request queue: 6
    10:02:14.473 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 000000000000000001b354ea9893bdbd317923adc51ad7e0e0fc59f55f97a830 at height 543964
    10:02:14.476 [DEBUG] [bitcoin/handleMerkleBlockMsg] Requesting block 0000000000000000000a055644ec7ee5404215fa4165bda207592d348c4593c6, len request queue: 5
    10:02:14.628 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 0000000000000000000a055644ec7ee5404215fa4165bda207592d348c4593c6 at height 543965
    10:02:14.628 [DEBUG] [bitcoin/handleMerkleBlockMsg] Requesting block 000000000000000001866f49d148be897bf79476fae16d77eb2ae8b58af5a7dd, len request queue: 4
    10:02:14.782 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 000000000000000001866f49d148be897bf79476fae16d77eb2ae8b58af5a7dd at height 543966
    10:02:14.785 [DEBUG] [bitcoin/handleMerkleBlockMsg] Requesting block 000000000000000000316a42589d9fc68253e93eef1330be40e2f88e36614bfa, len request queue: 3
    10:02:14.978 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 000000000000000000316a42589d9fc68253e93eef1330be40e2f88e36614bfa at height 543967
    10:02:14.981 [DEBUG] [bitcoin/handleMerkleBlockMsg] Requesting block 0000000000000000012ecb2fc76be688500a5879de4f612ab08626131532c459, len request queue: 2
    10:02:15.138 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 0000000000000000012ecb2fc76be688500a5879de4f612ab08626131532c459 at height 543968
    10:02:15.141 [DEBUG] [bitcoin/handleMerkleBlockMsg] Requesting block 000000000000000001ac46492c86ff7bff63f032b9a10616b56ac352443f1640, len request queue: 1
    10:02:15.296 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 000000000000000001ac46492c86ff7bff63f032b9a10616b56ac352443f1640 at height 543969
    10:02:15.299 [DEBUG] [bitcoin/handleMerkleBlockMsg] Requesting block 000000000000000000f549bfbb0bb1f5d7a2eebeb1ad1714ff44ebad5c7bf5cd, len request queue: 0
    10:02:15.455 [INFO] [bitcoin/handleMerkleBlockMsg] Received merkle block 000000000000000000f549bfbb0bb1f5d7a2eebeb1ad1714ff44ebad5c7bf5cd at height 543970
    10:04:11.563 [DEBUG] [bitcoin/onDisconnection] Peer 1.2.3.4:8333 (outbound) disconnected
    10:04:12.402 [DEBUG] [bitcoin/onDisconnection] Peer 5.6.7.8:8333 (outbound) disconnected
    10:04:13.102 [DEBUG] [bitcoin/onDisconnection] Peer 9.10.11.12:8333 (outbound) disconnected
    10:04:13.535 [DEBUG] [bitcoin/onVerack] Connected to 13.14.15.16:8333 - /Bitcoin ABC:0.17.1(EB32.0)/
    10:05:31.966 [INFO] [bitcoin/Close] Disconnecting from peers and shutting down

**Comment by jjeffryes** [comment]
@webunraveling and @placer14 has any progress been made here?

**Comment by webunraveling** [comment]
@jjeffryes and @placer14 so far the order is still showing a status of "Awaiting payment". I'm open to more suggestions.

**Comment by placer14** [comment]
Hey @webunraveling. Sorry for taking so long to respond. Would you mind posting a copy of your purchase contract in an issue at https://openbazaar.zendesk.com/hc/en-us/requests/new and reference this issue comment in the body? I'm not sure why a payment would not be detected by the wallet and I'm suspicious of your payment address. I'd also welcome links to the transaction on a blockchain explorer.

**Comment by webunraveling** [comment]
No problem. I submitted the info at the link you provided. Hopefully we can nail this down. :-)

**Comment by jjeffryes** [comment]
@placer14 what's the status of this issue?

**Comment by placer14** [comment]
@jjeffryes I'm afraid I don't have an update on this. This was put on the back-burner and was never recovered. Thank you for raising again, I'll put this back into the queue.
