### ISSUE TITLE
Cannot complete moderated order with ZEC. 

### ISSUE THREAD

**Issue by ulrichard** [OpenBazaar/openbazaar-desktop#1854]
Brief Description: 
Cannot complete moderated order with ZEC. 

Operating System (OS and version): ubuntu 16.04 / 18.04
OpenBazaar version (shown on `About OpenBazaar` page in menu): 2.3.7 and previous
Hardware: Dell XPS 13 DE / Intel NUC scull candy

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

I bought an item with moderation that was listed for ZEC.
After receiving the item and being satisfied with it, I wanted to complete the trade, to release the funds to the seller. But I get the following message: "There was an error completing the order. error broadcasting tx: status not ok: 400 Bad Request"
When I click on the moderator, I get the following error: "Failed to connect. There was an issue connecting to QmZPeZjm…. Please try again."

Observed Behavior:
Cannot release funds to the merchant.

Expected Behavior:
Closing the trade.

Additional info (links, images, etc go here):
The seller told me he used a mobile app to interact with OB.
I tried to complete the order many times over the last couple of days, but the result is always the same. I never had anything similar happen in the past. But in the past I always used BTC to pay.

**Comment by jjeffryes** [comment]
@ulrichard we are preparing a new 2.3.8 release right now that should fix this issue. Please stay tuned!

**Comment by ulrichard** [comment]
I still get the same error with the 2.3.8 version.
Is there anything else I can try on my end?

**Comment by placer14** [comment]
@ulrichard could you [find your `logs/ob.log` file](https://openbazaar.zendesk.com/hc/en-us/articles/360022335771-Where-is-my-OpenBazaar-data-) and send it to us via https://openbazaar.zendesk.com/hc/en-us/requests/new?

**Comment by ulrichard** [comment]
I sent the logs a while ago, but didn't receive any feedback so far.
In the meantime, the moderator appears to be online again.
How are the chances that we can release the funds, when I click on the dispute button to let the moderator release the funds to the seller?

**Comment by jjeffryes** [comment]
It might be best to hold off on moderation for now. We've had a few reports of similar issues, and haven't been able to find a fix yet.

**Comment by wristeks** [comment]
i am having a very similar issue but i am the seller, i cant claim funds, i cant dispute, ZEC has no timer, cant turn over to moderator to release payment, all prices on inventory have changed to $NaN, in apps(but price shows in browser where you cant buy) so i cant make any sales, essentialy my funds are stuck 
 i have issue collecting payment, messaging buyers, and hitting dispute button, all get errors, i have moderator. waited 40days for payments to autorelease, but when i hit collect funds i get " There was an error claiming the payment."
ZEC order have no timer and when i hit dispute i get "There was an error completing the order.
unable to open case because order is too old to dispute"  so i cant send to moderator.  All of my orders were filled and delivered. one person also started a dispute with me when i never saw an order for them, claiming they paid me. can you please help solve this.
